spring:
  ##redis
   redis:
     cluster:
       nodes:
         - 192.168.0.31:7000
         - 192.168.0.32:7002
         - 192.168.0.33:7004
       max-redirects: 5

   ##datasource
   datasource:
     url: jdbc:mysql://192.168.0.10:3306/Order?characterEncoding=utf8
     username: root
     password: 123456
     driver-class-name: com.mysql.cj.jdbc.Driver

##basic
server:
  port: 8088

##mybatis
mybatis:
  mapper-locations: classpath:mybatis/mapper/*_mapper.xml
  type-aliases-package: com.lh.stock.lhstock.po
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


logging:
  config: classpath:spring-logback.xml
  pattern:
    console: "%d - %msg%n"
  level:
    root: info
